- hosts: localhost
  vars:
    user: "{{ ansible_env.USER }}"
    distro: "{{ ansible_distribution }}"
  tasks:
    - name: Print variable
      debug:
        var: user
    - name: print distro
      debug:
        var: distro


# - hosts: localhost
#   vars:
#     distro: "{{ ansible_distribution }}"
#     user: "{{ ansible_env.USER }}"
#     ipaddr: "{{ ansible_default_ipv4.address }}"
#   connection: local
#   become: true

#   pre_tasks:
#     - name: pre-run | check requirements
#       become_user: "{{ user }}" 
#       tags: always
#       package:
#         name: "{{ item }}"
#         state: latest
#       loop:
#         - python-psutil
#         - python-pip
#         - python-setuptools

#     - name: Install github module
#       ansible.builtin.pip:
#         name: github3.py

#     - name: Enable Multilib
#       replace:
#         path: "/etc/pacman.conf"
#         regexp: '#\[multilib]\n#Include = \/etc\/pacman.d\/mirrorlist'
#         replace: |
#           [multilib]
#           Include = /etc/pacman.d/mirrorlist
#       when: distro == 'Archlinux'

# - hosts: localhost
#   connection: local
#   become: true
#   vars:
#     distro: "{{ ansible_distribution }}"

#   tasks:
#     - name: software | unzip | install package
#       tags: unzip, packages, workstation-packages
#       package:
#         name: unzip
#         state: latest
